language: java
jdk:
  - openjdk17

services:
  - docker

before_install:
  - chmod +x mvnw

install:
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - ./mvnw clean verify -B
  - ./mvnw test

deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: sistema-carros-usuarios
  on:
    branch: develop